volumes:
  tesla_ble:
    external: true

services:   
  tesla_ble:
    container_name: tesla_ble
    image: "iainbullock/tesla_ble:latest"
 
    environment:
      - TZ='Europe/London'
      
    stdin_open: true
    tty: true         

    volumes:
      - tesla_ble:/data
      - /run/dbus:/run/dbus
        
    network_mode: host

    restart: no
    #restart: unless-stopped  
