volumes:
  tesla_ble:
    external: true

services:   
  tesla_ble:
    container_name: tesla_ble
    image: "iainbullock/tesla_ble_mqtt:latest"
 
    environment:
      - TZ='Europe/London'
      - TESLA_VIN=00000000000000000
      - MQTT_IP=127.0.0.1
      - MQTT_PORT=1883
      - MQTT_USER=
      - MQTT_PWD=
      
    stdin_open: true
    tty: true    
    
    entrypoint: "/app/run.sh"
    working_dir: /data
    
    volumes:
      - tesla_ble:/data
      - /run/dbus:/run/dbus
        
    network_mode: host
    privileged: true 

    restart: no
    #restart: unless-stopped  
